import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {installMathPreview} from './build/test-exports.mjs';
const dom=new JSDOM('<!doctype html><math-inline class="math-node"><div class="math-src" tabindex="0"></div><div class="math-render"></div></math-inline>',{pretendToBeVisual:true});
const win=dom.window,doc=win.document,source=doc.querySelector('.math-src'),render=doc.querySelector('.math-render');
let now=0,id=0,text='x',renders=0;
const timers=new Map(),frames=new Map();
win.setTimeout=(fn,delay)=>{timers.set(++id,{fn,at:now+delay});return id;};
win.clearTimeout=id=>timers.delete(id);
win.requestAnimationFrame=fn=>{frames.set(++id,fn);return id;};
win.cancelAnimationFrame=id=>frames.delete(id);
const math={_innerView:{state:{doc:{get textContent(){return text;}}}},_mathRenderElt:render,renderMath(){renders++;render.textContent=text;}};
doc.querySelector('.math-node').pmViewDesc={spec:math};
source.focus();
async function step(ms=0){
 now+=ms;await Promise.resolve();
 for(const [id,t] of [...timers])if(t.at<=now){timers.delete(id);t.fn();}
 for(const [id,fn] of [...frames]){frames.delete(id);fn();}
 await Promise.resolve();
}
async function type(value){text=value;source.dispatchEvent(new win.Event('input',{bubbles:true}));await step();}
const popup=()=>doc.getElementById('latex-suite-math-preview');
let stop=installMathPreview(win,100);
await step();assert.equal(renders,0);
await step(100);assert.equal(renders,1);assert.equal(popup().firstChild.textContent,'x');
await type('xy');await step(50);await type('xyz');await step(50);
assert.equal(renders,1);assert.equal(popup().firstChild.textContent,'x');
win.dispatchEvent(new win.Event('resize'));await step();
await step(50);assert.equal(renders,2);assert.equal(popup().firstChild.textContent,'xyz');
await type('pending');source.dispatchEvent(new win.Event('compositionstart',{bubbles:true}));
await step(200);assert.equal(renders,2);
source.dispatchEvent(new win.Event('compositionend',{bubbles:true}));await step();await step(100);assert.equal(renders,3);
await type('discard');source.blur();await step();await step(100);
assert.equal(renders,3);assert.equal(popup(),null);
source.focus();await step();stop();await step(200);
assert.equal(renders,3);assert.equal(popup(),null);assert.equal(timers.size,0);assert.equal(frames.size,0);
stop=installMathPreview(win,0);await step();assert.equal(renders,4);
await type('immediate');assert.equal(renders,5);stop();
stop=installMathPreview(win,250);await step();await step(249);assert.equal(renders,5);
await step(1);assert.equal(renders,6);stop();
stop=installMathPreview(win,NaN);await step();await step(99);assert.equal(renders,6);
await step(1);assert.equal(renders,7);stop();
// Gecko's inline wrapper may cover just the final line of a wrapped editor.
math._innerView.dom=source;
const node=doc.querySelector('.math-node');
node.getBoundingClientRect=()=>new win.DOMRect(20,450,400,20);
source.getBoundingClientRect=()=>new win.DOMRect(20,300,400,170);
stop=installMathPreview(win,0);await step();
Object.defineProperty(popup(),'offsetHeight',{value:80});
Object.defineProperty(popup(),'offsetWidth',{value:200});
win.dispatchEvent(new win.Event('resize'));await step();
assert.equal(popup().style.top,'214px','preview is above all wrapped source lines');
const blocker=doc.createElement('div');blocker.id='latex-suite-completion';
blocker.getBoundingClientRect=()=>new win.DOMRect(20,0,200,300);
doc.body.append(blocker);await step();
assert.equal(popup().style.visibility,'','completion overlap does not hide or move preview');
assert.equal(popup().style.top,'214px');
blocker.remove();await step();assert.equal(popup().style.visibility,'');
assert.equal(popup().style.top,'214px');
source.getBoundingClientRect=()=>new win.DOMRect(20,20,400,170);
node.getBoundingClientRect=()=>new win.DOMRect(20,170,400,20);
win.dispatchEvent(new win.Event('resize'));await step();
assert.equal(popup().style.visibility,'hidden','insufficient room above hides instead of flipping');
const menu=doc.createElement('div');menu.id='latex-suite-completion';
menu.getBoundingClientRect=()=>new win.DOMRect(20,195,200,200);
doc.body.append(menu);await step();
assert.equal(popup().style.visibility,'hidden','completion cannot force preview below');
source.getBoundingClientRect=()=>new win.DOMRect(20,0,400,win.innerHeight);
win.dispatchEvent(new win.Event('resize'));await step();
assert.equal(popup().style.visibility,'hidden','no room must not obscure source');
source.getBoundingClientRect=()=>new win.DOMRect(20,300,400,170);
node.getBoundingClientRect=()=>new win.DOMRect(20,450,400,20);
menu.remove();doc.dispatchEvent(new win.Event('scroll'));await step();
assert.equal(popup().style.visibility,'');assert.equal(popup().style.top,'214px');
assert.equal(win.getComputedStyle(popup()).pointerEvents,'auto','preview receives pointer input');
assert.equal(win.getComputedStyle(popup()).overflow,'auto');
assert.ok(Math.abs(parseFloat(win.getComputedStyle(popup()).maxHeight)-win.innerHeight*.35)<.01,'floating inline preview remains bounded');
const contentClick=new win.MouseEvent('mousedown',{bubbles:true,cancelable:true});
popup().firstChild.dispatchEvent(contentClick);assert.equal(contentClick.defaultPrevented,true,'formula click preserves source focus');
assert.equal(doc.activeElement,source);
const scrollbarClick=new win.MouseEvent('mousedown',{bubbles:true,cancelable:true});
popup().dispatchEvent(scrollbarClick);assert.equal(scrollbarClick.defaultPrevented,false,'native scrollbar dragging is allowed');
const wheelEvent=new win.WheelEvent('wheel',{bubbles:true,cancelable:true,deltaY:100});
popup().dispatchEvent(wheelEvent);assert.equal(wheelEvent.defaultPrevented,false,'wheel uses browser native scrolling');
await step();const beforeScroll=renders;
popup().scrollTop=40;popup().dispatchEvent(new win.Event('scroll',{bubbles:true}));
assert.equal(frames.size,0,'preview scrolling does not schedule positioning');
await step();assert.equal(renders,beforeScroll);assert.equal(popup().scrollTop,40);
stop();
const display=doc.createElement('math-display');display.className='math-node';
display.pmViewDesc={spec:math};display.append(source,render);node.replaceWith(display);
source.focus();stop=installMathPreview(win,0);await step();
assert.equal(popup().dataset.inline,'false');
assert.equal(win.getComputedStyle(popup()).maxHeight,'none','display preview has no height cap');
assert.equal(win.getComputedStyle(popup()).overflow,'auto','wide display preview still scrolls horizontally');
assert.equal(popup().parentNode,display,'display preview stays in note flow');
let outerClicks=0;display.addEventListener('mousedown',()=>outerClicks++);display.addEventListener('click',()=>outerClicks++);
math._innerView.focus=()=>source.focus();
const trackDown=new win.MouseEvent('mousedown',{bubbles:true,cancelable:true});
popup().dispatchEvent(trackDown);assert.equal(trackDown.defaultPrevented,false);
source.blur();await step();assert.ok(popup(),'scrollbar focus change does not close preview during drag');
doc.dispatchEvent(new win.MouseEvent('mouseup',{bubbles:true}));await step();
assert.equal(doc.activeElement,source,'drag release restores math source focus');
popup().dispatchEvent(new win.MouseEvent('click',{bubbles:true,cancelable:true}));
assert.equal(outerClicks,0,'scrollbar clicks do not reach outer math editor');
assert.ok(popup());
stop();
dom.window.close();
console.log('Preview debounce, retention, positioning events, IME and cleanup tests passed.');
