// Surface for test.js: the engine, plus the editor layer, which can be driven
// headlessly with prosemirror-model/-state (no DOM needed).
export { DEFAULT_SETTINGS, DEFAULT_SNIPPETS, processSettings } from "./settings/settings";
export { parseSnippets, parseSnippetVariables, parseKeyName, keyNameFromEvent } from "./snippets/parse";
export { scanScopes, Context } from "./utils/context";
export { scanEquations, mathBoundsAt, renderableEquations } from "./utils/math_bounds";
export { tabstopSpecsToTabstopGroups } from "./snippets/tabstop";
export { asMathReplacement } from "./editor/insert_math";
export { Options } from "./snippets/options";
export { IncludedEnvironmentResult } from "./snippets/snippets";
export { PMBuffer, rememberSelectionClass } from "./editor/pm";
export { expandSnippet, setSelectionToNextTabstop, clearTabstops, clearTabstopsIfElsewhere, hasTabstops } from "./snippets/snippet_management";
export { runSnippets, expand } from "./features/run_snippets";
export { currentBuffer } from "./editor/index";
export { autoEnlargeBrackets } from "./features/auto_enlarge_brackets";
export { runAutoFraction } from "./features/autofraction";
export { renderMath, unrenderMath, syncRender, isRendered } from "./render/math";
export { segmentsOf, domPointAt, offsetOfPoint, selectionOffsets, setCaret } from "./render/segments";
export { installPopupEnlarge } from "./reader/popup_enlarge";
export { DEFAULT_COMMANDS, parseCommands, candidates, tokenAt, replacementOf } from "./completion/dictionary";
export { installCompletion } from "./completion/controller";
export { expandCompletion } from "./snippets/snippet_management";
export { normalizeMathPaste, installMathPaste, mathPasteTransaction } from "./features/paste_math";
export { installMathPreview } from "./features/math_preview";
export { PREVIEW_CARET, previewMarkerColor, previewMarkerSource, renderPreviewMarker } from "./features/preview_marker";
export { createMathSourceMap, mathCaretAt, installMathCaret } from "./features/math_caret";
export { latexTokens, installMathHighlight } from "./features/math_highlight";
export { deleteMathWord } from "./features/math_delete";
export { deleteMathNode } from "./editor/pm";
export { installNoteMenu } from "./features/note_menu";
export { commitImageSize, installImageResize } from "./features/image_resize";
export { annotationToken, annotationMatches, installAnnotationCompletion } from "./features/annotation_completion";
export { WordIndex, BufferWords, TextSources, textToken, parseWordList } from "./features/text_sources";
export { installScrollPastEnd } from "./features/scroll_past_end";
export { TextBuffer } from "./editor/contenteditable";
export { mathSelectionRegions, mathDelimiterIndex, createMathSelection, createMathDragSelection, installMathMouseSelection, normalizeMathClickTimeout } from "./features/math_selection";
export { installMathVisibility } from "./features/math_visibility";
export { newlineMatrixShortcut, lineBreakMatrixShortcut, exitMatrixShortcut } from "./features/matrix_shortcuts";
